# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e9e2c11bd37aed3fccf2c747cbe31fa"
name = "Product QR Code"
application_url = "https://simply-tales-wagon-sitting.trycloudflare.com"
embedded = true
handle = "product-qr-code"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://simply-tales-wagon-sitting.trycloudflare.com/auth/callback", "https://simply-tales-wagon-sitting.trycloudflare.com/auth/shopify/callback", "https://simply-tales-wagon-sitting.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
